get_facts:
    cisco_ios_ssh:
        config_register: '0xF'
    fqdn: N/A
    hostname: Cacuaco
    interfaces:
    - Vlan1
    - Vlan3
    - Vlan56
    - Vlan99
    - Vlan106
    - FastEthernet0
    - GigabitEthernet1/0/1
    - GigabitEthernet1/0/2
    - GigabitEthernet1/0/3
    - GigabitEthernet1/0/4
    - GigabitEthernet1/0/5
    - GigabitEthernet1/0/6
    - GigabitEthernet1/0/7
    - GigabitEthernet1/0/8
    - GigabitEthernet1/0/9
    - GigabitEthernet1/0/10
    - GigabitEthernet1/0/11
    - GigabitEthernet1/0/12
    - GigabitEthernet1/0/13
    - GigabitEthernet1/0/14
    - GigabitEthernet1/0/15
    - GigabitEthernet1/0/16
    - GigabitEthernet1/0/17
    - GigabitEthernet1/0/18
    - GigabitEthernet1/0/19
    - GigabitEthernet1/0/20
    - GigabitEthernet1/0/21
    - GigabitEthernet1/0/22
    - GigabitEthernet1/0/23
    - GigabitEthernet1/0/24
    - GigabitEthernet1/0/25
    - GigabitEthernet1/0/26
    - GigabitEthernet1/0/27
    - GigabitEthernet1/0/28
    - GigabitEthernet1/0/29
    - GigabitEthernet1/0/30
    - GigabitEthernet1/0/31
    - GigabitEthernet1/0/32
    - GigabitEthernet1/0/33
    - GigabitEthernet1/0/34
    - GigabitEthernet1/0/35
    - GigabitEthernet1/0/36
    - GigabitEthernet1/0/37
    - GigabitEthernet1/0/38
    - GigabitEthernet1/0/39
    - GigabitEthernet1/0/40
    - GigabitEthernet1/0/41
    - GigabitEthernet1/0/42
    - GigabitEthernet1/0/43
    - GigabitEthernet1/0/44
    - GigabitEthernet1/0/45
    - GigabitEthernet1/0/46
    - GigabitEthernet1/0/47
    - GigabitEthernet1/0/48
    - GigabitEthernet1/1/1
    - GigabitEthernet1/1/2
    - GigabitEthernet1/1/3
    - GigabitEthernet1/1/4
    - Te1/1/1
    - Te1/1/2
    model: WS-C3750X-48P
    os_version: 12.2(55)SE5
    serial_number: FDO1749H108
    uptime: 24060
    uptime_string: 00:06:41:00
    vendor: cisco
    vlans:
    - '1'
    - '3'
    - '56'
    - '99'
    - '106'
    - '1002'
    - '1003'
    - '1004'
    - '1005'
changed: false
failed: false
